// Mocks generated by Mockito 5.0.16 from annotations
// in sample_app/test/widget/news_tile_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sample_app/models/news.dart' as _i2;
import 'package:sample_app/services/hacker_news_service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeNews_0 extends _i1.Fake implements _i2.News {}

/// A class which mocks [HackerNewsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHackerNewsService extends _i1.Mock implements _i3.HackerNewsService {
  MockHackerNewsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FutureOr<List<int>> getTopNewsId() =>
      (super.noSuchMethod(Invocation.method(#getTopNewsId, []),
              returnValue: Future<List<int>>.value(<int>[]))
          as _i4.FutureOr<List<int>>);
  @override
  _i4.FutureOr<_i2.News> getNews(int? id) =>
      (super.noSuchMethod(Invocation.method(#getNews, [id]),
              returnValue: Future<_i2.News>.value(_FakeNews_0()))
          as _i4.FutureOr<_i2.News>);
  @override
  String toString() => super.toString();
}
